version: "3"
services:
    app_service:
        build: ./app/
        image: ltneric/ltn2017:latest
        volumes:
        #  - $PWD/app:/app
          - $PWD:/var/log/
        environment:
          - DEBUG="True"
        env_file:
          - secrets.env